// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/source/source.proto

package go_micro_service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SourceRequest struct {
	SourceTag            string   `protobuf:"bytes,1,opt,name=sourceTag,proto3" json:"sourceTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceRequest) Reset()         { *m = SourceRequest{} }
func (m *SourceRequest) String() string { return proto.CompactTextString(m) }
func (*SourceRequest) ProtoMessage()    {}
func (*SourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d18926d0311f78f, []int{0}
}

func (m *SourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceRequest.Unmarshal(m, b)
}
func (m *SourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceRequest.Marshal(b, m, deterministic)
}
func (m *SourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceRequest.Merge(m, src)
}
func (m *SourceRequest) XXX_Size() int {
	return xxx_messageInfo_SourceRequest.Size(m)
}
func (m *SourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SourceRequest proto.InternalMessageInfo

func (m *SourceRequest) GetSourceTag() string {
	if m != nil {
		return m.SourceTag
	}
	return ""
}

type SourceResponse struct {
	SourceTag            string   `protobuf:"bytes,1,opt,name=sourceTag,proto3" json:"sourceTag,omitempty"`
	SystemSource         bool     `protobuf:"varint,2,opt,name=systemSource,proto3" json:"systemSource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceResponse) Reset()         { *m = SourceResponse{} }
func (m *SourceResponse) String() string { return proto.CompactTextString(m) }
func (*SourceResponse) ProtoMessage()    {}
func (*SourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d18926d0311f78f, []int{1}
}

func (m *SourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceResponse.Unmarshal(m, b)
}
func (m *SourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceResponse.Marshal(b, m, deterministic)
}
func (m *SourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceResponse.Merge(m, src)
}
func (m *SourceResponse) XXX_Size() int {
	return xxx_messageInfo_SourceResponse.Size(m)
}
func (m *SourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SourceResponse proto.InternalMessageInfo

func (m *SourceResponse) GetSourceTag() string {
	if m != nil {
		return m.SourceTag
	}
	return ""
}

func (m *SourceResponse) GetSystemSource() bool {
	if m != nil {
		return m.SystemSource
	}
	return false
}

func init() {
	proto.RegisterType((*SourceRequest)(nil), "go.micro.service.user.SourceRequest")
	proto.RegisterType((*SourceResponse)(nil), "go.micro.service.user.SourceResponse")
}

func init() {
	proto.RegisterFile("proto/source/source.proto", fileDescriptor_1d18926d0311f78f)
}

var fileDescriptor_1d18926d0311f78f = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x85, 0x52, 0x7a, 0x60, 0x31, 0x21, 0xd1, 0xf4,
	0x7c, 0xbd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0xbd, 0xe2, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0xbd,
	0xd2, 0xe2, 0xd4, 0x22, 0x25, 0x5d, 0x2e, 0xde, 0x60, 0xb0, 0xb2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0x21, 0x19, 0x2e, 0x4e, 0x88, 0xbe, 0x90, 0xc4, 0x74, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x84, 0x80, 0x52, 0x10, 0x17, 0x1f, 0x4c, 0x79, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a,
	0x7e, 0xf5, 0x42, 0x4a, 0x5c, 0x3c, 0xc5, 0x95, 0xc5, 0x25, 0xa9, 0xb9, 0x10, 0x5d, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x28, 0x62, 0x46, 0x99, 0x5c, 0x6c, 0x10, 0x96, 0x50, 0x3c, 0x17,
	0x9f, 0x7b, 0x6a, 0x89, 0x53, 0x65, 0x30, 0x5c, 0xbf, 0x8a, 0x1e, 0x56, 0x67, 0xeb, 0xa1, 0xb8,
	0x59, 0x4a, 0x95, 0x80, 0x2a, 0x88, 0x53, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x61, 0x61, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x1d, 0x2d, 0xd7, 0xd5, 0x28, 0x01, 0x00, 0x00,
}
