// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewUserRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Contact              string   `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`
	OrganizationName     string   `protobuf:"bytes,6,opt,name=organizationName,proto3" json:"organizationName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserRequest) Reset()         { *m = NewUserRequest{} }
func (m *NewUserRequest) String() string { return proto.CompactTextString(m) }
func (*NewUserRequest) ProtoMessage()    {}
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *NewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRequest.Unmarshal(m, b)
}
func (m *NewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRequest.Marshal(b, m, deterministic)
}
func (m *NewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRequest.Merge(m, src)
}
func (m *NewUserRequest) XXX_Size() int {
	return xxx_messageInfo_NewUserRequest.Size(m)
}
func (m *NewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRequest proto.InternalMessageInfo

func (m *NewUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *NewUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *NewUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUserRequest) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *NewUserRequest) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type UserByIdRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserByIdRequest) Reset()         { *m = UserByIdRequest{} }
func (m *UserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*UserByIdRequest) ProtoMessage()    {}
func (*UserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *UserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserByIdRequest.Unmarshal(m, b)
}
func (m *UserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserByIdRequest.Marshal(b, m, deterministic)
}
func (m *UserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserByIdRequest.Merge(m, src)
}
func (m *UserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_UserByIdRequest.Size(m)
}
func (m *UserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserByIdRequest proto.InternalMessageInfo

func (m *UserByIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserByEmailRequest) Reset()         { *m = UserByEmailRequest{} }
func (m *UserByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UserByEmailRequest) ProtoMessage()    {}
func (*UserByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *UserByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserByEmailRequest.Unmarshal(m, b)
}
func (m *UserByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserByEmailRequest.Marshal(b, m, deterministic)
}
func (m *UserByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserByEmailRequest.Merge(m, src)
}
func (m *UserByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UserByEmailRequest.Size(m)
}
func (m *UserByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserByEmailRequest proto.InternalMessageInfo

func (m *UserByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserDetails struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Contact              string   `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	OrganizationId       string   `protobuf:"bytes,6,opt,name=organizationId,proto3" json:"organizationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetails) Reset()         { *m = UserDetails{} }
func (m *UserDetails) String() string { return proto.CompactTextString(m) }
func (*UserDetails) ProtoMessage()    {}
func (*UserDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *UserDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetails.Unmarshal(m, b)
}
func (m *UserDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetails.Marshal(b, m, deterministic)
}
func (m *UserDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetails.Merge(m, src)
}
func (m *UserDetails) XXX_Size() int {
	return xxx_messageInfo_UserDetails.Size(m)
}
func (m *UserDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetails.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetails proto.InternalMessageInfo

func (m *UserDetails) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserDetails) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserDetails) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserDetails) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *UserDetails) GetOrganizationId() string {
	if m != nil {
		return m.OrganizationId
	}
	return ""
}

type UpdateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Contact              string   `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateUserRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *UpdateUserRequest) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func init() {
	proto.RegisterType((*NewUserRequest)(nil), "go.micro.service.user.NewUserRequest")
	proto.RegisterType((*Response)(nil), "go.micro.service.user.Response")
	proto.RegisterType((*UserByIdRequest)(nil), "go.micro.service.user.UserByIdRequest")
	proto.RegisterType((*UserByEmailRequest)(nil), "go.micro.service.user.UserByEmailRequest")
	proto.RegisterType((*UserDetails)(nil), "go.micro.service.user.UserDetails")
	proto.RegisterType((*UpdateUserRequest)(nil), "go.micro.service.user.UpdateUserRequest")
}

func init() {
	proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7)
}

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x0e, 0xd2, 0x40,
	0x10, 0xa5, 0x05, 0x4a, 0x19, 0x13, 0xd4, 0x89, 0x90, 0x86, 0x98, 0x68, 0x36, 0x91, 0x00, 0x87,
	0x9a, 0xe8, 0xd5, 0x13, 0x62, 0x4c, 0x2f, 0x1c, 0x9a, 0x10, 0x4f, 0x1e, 0xd6, 0x76, 0x24, 0x9b,
	0xd0, 0x2e, 0xee, 0x2e, 0x18, 0xfc, 0x09, 0xff, 0xc2, 0xab, 0xdf, 0xe5, 0x5f, 0x98, 0x2e, 0x2d,
	0x16, 0xb4, 0x84, 0x83, 0x97, 0x26, 0x6f, 0xe7, 0xe5, 0xe5, 0xcd, 0x9b, 0x97, 0xc2, 0x70, 0xa7,
	0xa4, 0x91, 0x2f, 0xf7, 0x9a, 0x94, 0xfd, 0x84, 0x16, 0xe3, 0x70, 0x23, 0xc3, 0x4c, 0x24, 0x4a,
	0x86, 0x9a, 0xd4, 0x41, 0x24, 0x14, 0x16, 0x43, 0xf6, 0xc3, 0x81, 0xc1, 0x8a, 0xbe, 0xae, 0x35,
	0xa9, 0x98, 0xbe, 0xec, 0x49, 0x1b, 0x7c, 0x0a, 0xfd, 0xcf, 0x42, 0x69, 0xb3, 0xe2, 0x19, 0x05,
	0xce, 0x73, 0x67, 0xda, 0x8f, 0xff, 0x3c, 0xe0, 0x18, 0xfc, 0x2d, 0x2f, 0x87, 0xae, 0x1d, 0x9e,
	0x31, 0x3e, 0x81, 0x2e, 0x65, 0x5c, 0x6c, 0x83, 0xb6, 0x1d, 0x9c, 0x00, 0x06, 0xd0, 0x4b, 0x64,
	0x6e, 0x78, 0x62, 0x82, 0x8e, 0x7d, 0xaf, 0x20, 0xce, 0xe1, 0x91, 0x54, 0x1b, 0x9e, 0x8b, 0x6f,
	0xdc, 0x08, 0x99, 0x5b, 0x4d, 0xcf, 0x52, 0xfe, 0x7a, 0x67, 0x6f, 0xc0, 0x8f, 0x49, 0xef, 0x64,
	0xae, 0xa9, 0x50, 0xcc, 0x48, 0x6b, 0xbe, 0xa9, 0xfc, 0x55, 0x10, 0x47, 0xe0, 0x69, 0xc3, 0xcd,
	0x5e, 0x5b, 0x6f, 0x7e, 0x5c, 0x22, 0x36, 0x83, 0x87, 0xc5, 0x8a, 0x8b, 0x63, 0x94, 0x56, 0x6b,
	0x8e, 0xc0, 0x2b, 0x12, 0x88, 0xd2, 0x52, 0xa3, 0x44, 0x6c, 0x0e, 0x78, 0xa2, 0xbe, 0x2b, 0xdc,
	0x57, 0xec, 0xf3, 0x6a, 0x4e, 0x6d, 0x35, 0xf6, 0xd3, 0x81, 0x07, 0x05, 0x79, 0x49, 0x86, 0x8b,
	0xad, 0xc6, 0x01, 0xb8, 0xa2, 0xd2, 0x73, 0x45, 0x7a, 0x19, 0xa5, 0x7b, 0x2b, 0xca, 0x76, 0x53,
	0x94, 0x9d, 0x86, 0x28, 0xbb, 0x97, 0x51, 0x4e, 0x60, 0x50, 0x8f, 0x2c, 0x4a, 0xcb, 0x20, 0xaf,
	0x5e, 0xd9, 0x77, 0x07, 0x1e, 0xaf, 0x77, 0x29, 0x37, 0x54, 0x3f, 0xf9, 0xff, 0xf3, 0x3d, 0x02,
	0x8f, 0x27, 0x46, 0x1c, 0xc8, 0x1a, 0xf7, 0xe3, 0x12, 0x35, 0x3b, 0x7f, 0xf5, 0xcb, 0x85, 0x4e,
	0xe1, 0x05, 0x63, 0xf0, 0xde, 0x2a, 0xe2, 0x86, 0xf0, 0x45, 0xf8, 0xcf, 0xb2, 0x86, 0x97, 0x45,
	0x1d, 0x3f, 0x6b, 0xa0, 0x55, 0x3d, 0x61, 0x2d, 0xfc, 0x00, 0xbd, 0xf7, 0x64, 0x16, 0xc7, 0x68,
	0x89, 0x93, 0x06, 0xf6, 0x55, 0x2f, 0xc6, 0xec, 0x06, 0xaf, 0xbc, 0x33, 0x6b, 0xe1, 0x47, 0x00,
	0x2b, 0x6c, 0x4b, 0x82, 0xb3, 0x9b, 0xda, 0xf5, 0x22, 0xdd, 0x29, 0xbf, 0x06, 0xef, 0x74, 0x25,
	0x9c, 0x36, 0xf1, 0xaf, 0x8f, 0x78, 0x47, 0x1c, 0x9f, 0x3c, 0xfb, 0x2f, 0x78, 0xfd, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x02, 0x36, 0xae, 0xc6, 0x24, 0x04, 0x00, 0x00,
}
